package com.fehmidev.projectmanagement.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ActivityLogAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertActivityLogAllPropertiesEquals(ActivityLog expected, ActivityLog actual) {
        assertActivityLogAutoGeneratedPropertiesEquals(expected, actual);
        assertActivityLogAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertActivityLogAllUpdatablePropertiesEquals(ActivityLog expected, ActivityLog actual) {
        assertActivityLogUpdatableFieldsEquals(expected, actual);
        assertActivityLogUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertActivityLogAutoGeneratedPropertiesEquals(ActivityLog expected, ActivityLog actual) {
        assertThat(actual)
            .as("Verify ActivityLog auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertActivityLogUpdatableFieldsEquals(ActivityLog expected, ActivityLog actual) {
        assertThat(actual)
            .as("Verify ActivityLog relevant properties")
            .satisfies(a -> assertThat(a.getAction()).as("check action").isEqualTo(expected.getAction()))
            .satisfies(a -> assertThat(a.getEntityName()).as("check entityName").isEqualTo(expected.getEntityName()))
            .satisfies(a -> assertThat(a.getEntityId()).as("check entityId").isEqualTo(expected.getEntityId()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertActivityLogUpdatableRelationshipsEquals(ActivityLog expected, ActivityLog actual) {
        assertThat(actual)
            .as("Verify ActivityLog relationships")
            .satisfies(a -> assertThat(a.getEmployee()).as("check employee").isEqualTo(expected.getEmployee()));
    }
}
