package com.fehmidev.projectmanagement.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ChecklistAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChecklistAllPropertiesEquals(Checklist expected, Checklist actual) {
        assertChecklistAutoGeneratedPropertiesEquals(expected, actual);
        assertChecklistAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChecklistAllUpdatablePropertiesEquals(Checklist expected, Checklist actual) {
        assertChecklistUpdatableFieldsEquals(expected, actual);
        assertChecklistUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChecklistAutoGeneratedPropertiesEquals(Checklist expected, Checklist actual) {
        assertThat(actual)
            .as("Verify Checklist auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChecklistUpdatableFieldsEquals(Checklist expected, Checklist actual) {
        assertThat(actual)
            .as("Verify Checklist relevant properties")
            .satisfies(a -> assertThat(a.getTitle()).as("check title").isEqualTo(expected.getTitle()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChecklistUpdatableRelationshipsEquals(Checklist expected, Checklist actual) {
        assertThat(actual)
            .as("Verify Checklist relationships")
            .satisfies(a -> assertThat(a.getTask()).as("check task").isEqualTo(expected.getTask()));
    }
}
