package com.fehmidev.projectmanagement.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ChecklistItemAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChecklistItemAllPropertiesEquals(ChecklistItem expected, ChecklistItem actual) {
        assertChecklistItemAutoGeneratedPropertiesEquals(expected, actual);
        assertChecklistItemAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChecklistItemAllUpdatablePropertiesEquals(ChecklistItem expected, ChecklistItem actual) {
        assertChecklistItemUpdatableFieldsEquals(expected, actual);
        assertChecklistItemUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChecklistItemAutoGeneratedPropertiesEquals(ChecklistItem expected, ChecklistItem actual) {
        assertThat(actual)
            .as("Verify ChecklistItem auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChecklistItemUpdatableFieldsEquals(ChecklistItem expected, ChecklistItem actual) {
        assertThat(actual)
            .as("Verify ChecklistItem relevant properties")
            .satisfies(a -> assertThat(a.getContent()).as("check content").isEqualTo(expected.getContent()))
            .satisfies(a -> assertThat(a.getIsDone()).as("check isDone").isEqualTo(expected.getIsDone()))
            .satisfies(a -> assertThat(a.getPosition()).as("check position").isEqualTo(expected.getPosition()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChecklistItemUpdatableRelationshipsEquals(ChecklistItem expected, ChecklistItem actual) {
        assertThat(actual)
            .as("Verify ChecklistItem relationships")
            .satisfies(a -> assertThat(a.getChecklist()).as("check checklist").isEqualTo(expected.getChecklist()));
    }
}
