package com.fehmidev.projectmanagement.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ReportSnapshotAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReportSnapshotAllPropertiesEquals(ReportSnapshot expected, ReportSnapshot actual) {
        assertReportSnapshotAutoGeneratedPropertiesEquals(expected, actual);
        assertReportSnapshotAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReportSnapshotAllUpdatablePropertiesEquals(ReportSnapshot expected, ReportSnapshot actual) {
        assertReportSnapshotUpdatableFieldsEquals(expected, actual);
        assertReportSnapshotUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReportSnapshotAutoGeneratedPropertiesEquals(ReportSnapshot expected, ReportSnapshot actual) {
        assertThat(actual)
            .as("Verify ReportSnapshot auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReportSnapshotUpdatableFieldsEquals(ReportSnapshot expected, ReportSnapshot actual) {
        assertThat(actual)
            .as("Verify ReportSnapshot relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()))
            .satisfies(a -> assertThat(a.getGeneratedDate()).as("check generatedDate").isEqualTo(expected.getGeneratedDate()))
            .satisfies(a -> assertThat(a.getData()).as("check data").isEqualTo(expected.getData()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReportSnapshotUpdatableRelationshipsEquals(ReportSnapshot expected, ReportSnapshot actual) {
        assertThat(actual)
            .as("Verify ReportSnapshot relationships")
            .satisfies(a -> assertThat(a.getProject()).as("check project").isEqualTo(expected.getProject()));
    }
}
