package com.fehmidev.projectmanagement.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SprintAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSprintAllPropertiesEquals(Sprint expected, Sprint actual) {
        assertSprintAutoGeneratedPropertiesEquals(expected, actual);
        assertSprintAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSprintAllUpdatablePropertiesEquals(Sprint expected, Sprint actual) {
        assertSprintUpdatableFieldsEquals(expected, actual);
        assertSprintUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSprintAutoGeneratedPropertiesEquals(Sprint expected, Sprint actual) {
        assertThat(actual)
            .as("Verify Sprint auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSprintUpdatableFieldsEquals(Sprint expected, Sprint actual) {
        assertThat(actual)
            .as("Verify Sprint relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getGoal()).as("check goal").isEqualTo(expected.getGoal()))
            .satisfies(a -> assertThat(a.getStartDate()).as("check startDate").isEqualTo(expected.getStartDate()))
            .satisfies(a -> assertThat(a.getEndDate()).as("check endDate").isEqualTo(expected.getEndDate()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getCapacity()).as("check capacity").isEqualTo(expected.getCapacity()))
            .satisfies(a -> assertThat(a.getVelocity()).as("check velocity").isEqualTo(expected.getVelocity()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSprintUpdatableRelationshipsEquals(Sprint expected, Sprint actual) {
        assertThat(actual)
            .as("Verify Sprint relationships")
            .satisfies(a -> assertThat(a.getProject()).as("check project").isEqualTo(expected.getProject()));
    }
}
