package com.fehmidev.projectmanagement.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TimeEntryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTimeEntryAllPropertiesEquals(TimeEntry expected, TimeEntry actual) {
        assertTimeEntryAutoGeneratedPropertiesEquals(expected, actual);
        assertTimeEntryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTimeEntryAllUpdatablePropertiesEquals(TimeEntry expected, TimeEntry actual) {
        assertTimeEntryUpdatableFieldsEquals(expected, actual);
        assertTimeEntryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTimeEntryAutoGeneratedPropertiesEquals(TimeEntry expected, TimeEntry actual) {
        assertThat(actual)
            .as("Verify TimeEntry auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTimeEntryUpdatableFieldsEquals(TimeEntry expected, TimeEntry actual) {
        assertThat(actual)
            .as("Verify TimeEntry relevant properties")
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getStartTime()).as("check startTime").isEqualTo(expected.getStartTime()))
            .satisfies(a -> assertThat(a.getEndTime()).as("check endTime").isEqualTo(expected.getEndTime()))
            .satisfies(a -> assertThat(a.getHours()).as("check hours").isEqualTo(expected.getHours()))
            .satisfies(a -> assertThat(a.getEntryDate()).as("check entryDate").isEqualTo(expected.getEntryDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTimeEntryUpdatableRelationshipsEquals(TimeEntry expected, TimeEntry actual) {
        assertThat(actual)
            .as("Verify TimeEntry relationships")
            .satisfies(a -> assertThat(a.getTask()).as("check task").isEqualTo(expected.getTask()))
            .satisfies(a -> assertThat(a.getEmployee()).as("check employee").isEqualTo(expected.getEmployee()));
    }
}
